import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import type { SearchResponse } from "./company-finder/types";
import { getCountry } from "./company-finder/countries";
import { officialPageFor } from "./company-finder/official-pages";
import { resolveGreekFilingUrl } from "./company-finder/greek-filing";
import { numericRegistryId, searchGleif } from "./company-finder/sources/gleif";
import { brregOrgFromInput, fetchBrregAnnualReports } from "./company-finder/sources/bilanci/brreg-no";
import { fetchPolishEsefFinancials } from "./company-finder/sources/bilanci/poland-esef";
import { fetchRuzCompanyByDic, fetchRuzCompanyByIco, normalizeRuzDic, normalizeRuzIco, resolveRuzIcoByName } from "./company-finder/sources/bilanci/ruz-sk";
const searchSchema=z.object({query:z.string().max(200).default(""),vat:z.string().max(40).default(""),country:z.string().max(2).default("")});
const POLISH_KRS_REGISTRATION_AUTHORITY="RA000484";
function emptyResponse(warning:string):SearchResponse{return{found:false,sources:[],warnings:[warning],searchedAt:new Date().toISOString()}}
function toInPageDocumentUrl(documentUrl:string){return documentUrl.startsWith("/api/company-finder/document?")?documentUrl:`/api/company-finder/document?url=${encodeURIComponent(documentUrl)}`}
function firstRegistryIdentifier(response:SearchResponse,fallback:string){return response.company?.registry?.id?.trim()||fallback.trim()}
function hideSources(response:SearchResponse):SearchResponse{if(response.company?.nameSource){response.company={...response.company,nameSource:undefined}}if(response.financials){response.financials={...response.financials,source:undefined}}response.officialPage=undefined;response.sources=[];return response}
export interface PolishKrsResolution{krs?:string;detail?:string}
export async function resolvePolishKrsByName(query:string,timeoutMs=10000):Promise<PolishKrsResolution>{const term=query.trim();if(term.length<3)return{detail:"nome troppo corto per la risoluzione KRS"};const result=await searchGleif(term,"PL",timeoutMs);if(!result.ok)return{detail:result.error??"resolver GLEIF non raggiungibile"};for(const match of result.matches){if(match.country!=="PL"||match.registeredAt!==POLISH_KRS_REGISTRATION_AUTHORITY)continue;const registeredAs=numericRegistryId(match.registeredAs);if(!registeredAs)continue;const krs=registeredAs.padStart(10,"0");if(/^\d{10}$/.test(krs))return{krs,detail:`KRS ${krs} risolto da GLEIF → ${POLISH_KRS_REGISTRATION_AUTHORITY}`}}return{detail:"Nessuna entità polacca Registered At KRS (RA000484) con identificativo verificabile"}}
export async function attachNorwayFinancials(response:SearchResponse,identifier:string):Promise<SearchResponse>{if(response.company?.country.iso!=="NO")return response;const orgnr=brregOrgFromInput(identifier)||brregOrgFromInput(response.company?.registry?.id??"");if(!orgnr)return response;const result=await fetchBrregAnnualReports(orgnr);if(result.ok&&result.data){response.financials=result.data;response.company={...(response.company??{country:getCountry("NO")!}),country:{...(response.company?.country??getCountry("NO")!),financials:{free:true,note:"Bilanci annuali ufficiali gratuiti tramite Regnskapsregisteret Brønnøysundregistrene."}}};}return response}
async function resolveGreekBalance(response:SearchResponse,fallbackId:string):Promise<SearchResponse>{if(response.company?.country.iso!=="GR"||response.financials?.documentUrl)return response;const gemi=firstRegistryIdentifier(response,fallbackId).replace(/\D/g,"");if(!/^\d{10}$/.test(gemi))return response;const c=new AbortController(),timer=setTimeout(()=>c.abort(),15000);try{const filingUrl=await resolveGreekFilingUrl(gemi,c.signal);if(!filingUrl)return response;response.financials={...(response.financials??{available:false,years:[]}),documentUrl:filingUrl,documentTitle:"Bilancio ufficiale — ΓΕΜΗ / BusinessPortal iXBRL",source:"ΓΕΜΗ — BusinessPortal iXBRL",note:"Documento iXBRL ufficiale individuato direttamente per la società selezionata."};response.officialPage=undefined;return response}catch{return response}finally{clearTimeout(timer)}}
async function attachPolishEsefFinancials(response:SearchResponse,query:string):Promise<boolean>{try{const identifiers=response.company?.identifiers??[];let lei=identifiers.find(i=>i.key==="LEI")?.value;if(!lei){const term=response.company?.name?.trim()||query.trim();if(term.length<3)return false;const g=await searchGleif(term,"PL");if(!g.ok)return false;lei=g.matches[0]?.lei}if(!lei)return false;const r=await fetchPolishEsefFinancials(lei);if(!r.ok||!r.data)return false;const country=response.company?.country??getCountry("PL");if(!country)return false;response.found=true;response.company={name:response.company?.name?.trim()||query.trim()||"—",...(response.company??{}),country};response.financials=r.data;return true}catch{return false}}
async function attachSlovakFinancials(response:SearchResponse,identifier:string,kind:"ico"|"dic"):Promise<SearchResponse>{const result=kind==="ico"?await fetchRuzCompanyByIco(identifier):await fetchRuzCompanyByDic(identifier);if(!result.ok){response.warnings=[result.error??"Registro slovacco non disponibile",...response.warnings];return response}if(!result.data?.company?.name){response.found=false;response.company=undefined;response.financials=undefined;response.warnings=["Nessuna società slovacca trovata nel Registro slovacco dei bilanci.",...response.warnings];return response}const country=getCountry("SK")??{iso:"SK",nameIt:"Slovacchia",flag:"🇸🇰",vatPrefix:"SK",registryName:"Register účtovných závierok (RÚZ)",registryAuthority:"Ministerstvo financií Slovenskej republiky",financials:{free:true,note:"Registro slovacco dei bilanci (Registeruz)"}};response.found=true;response.company={name:result.data.company.name,country,registry:{name:country.registryName,authority:country.registryAuthority,id:result.data.company.ico},status:result.data.company.status,registeredSince:result.data.company.registeredSince,address:result.data.company.address,identifiers:[{key:"IČO",value:result.data.company.ico}]};response.financials=result.data.financials;response.sources=[];response.officialPage=undefined;return response}
async function resolveSlovakName(query:string):Promise<string|undefined>{return resolveRuzIcoByName(query)}
async function prioritizeBalanceDocument(response:SearchResponse,fallbackId:string):Promise<SearchResponse>{const resolved=await resolveGreekBalance(response,fallbackId),documentUrl=resolved.financials?.documentUrl;if(!documentUrl)return hideSources(resolved);resolved.financials={...resolved.financials!,documentUrl:toInPageDocumentUrl(documentUrl)};return hideSources(resolved)}
async function browserRegistryResponse(countryIso:string,identifier:string,query:string):Promise<SearchResponse|undefined>{const country=getCountry(countryIso);if(!country)return undefined;const officialPage=officialPageFor(countryIso,identifier,query);if(!officialPage)return undefined;const cleaned=identifier.trim();return prioritizeBalanceDocument({found:true,company:{name:query.trim()||`${country.nameIt} — ${cleaned}`,country,registry:{name:officialPage.label,authority:country.registryAuthority,id:cleaned}},financials:{available:false,years:[],note:"Consultazione del registro ufficiale."},sources:[{id:"official-browser",label:officialPage.label,state:"ok",detail:"consultazione ufficiale da browser"}],warnings:[],searchedAt:new Date().toISOString(),officialPage},cleaned)}
export const findCompany=createServerFn({method:"POST"}).inputValidator((data:unknown)=>searchSchema.parse(data??{})).handler(async({data}):Promise<SearchResponse>=>{const query=data.query.trim(),vat=data.vat.trim(),country=data.country.trim().toUpperCase(),rawVat=vat.replace(/[\s.-]/g,"").toUpperCase(),normalized=rawVat.replace(/^SK/,"");if(!query&&!vat)return emptyResponse("Inserisci la ragione sociale oppure il numero di partita IVA.");let slovakIco=country==="SK"?normalizeRuzIco(normalized):undefined;const slovakDic=country==="SK"?normalizeRuzDic(normalized):undefined;if(!slovakIco&&/^SK\d{8}$/.test(rawVat))slovakIco=normalizeRuzIco(rawVat.slice(2));if(country==="SK"&&slovakIco){const response=await attachSlovakFinancials(emptyResponse(""),slovakIco,"ico");response.warnings=response.warnings.filter(Boolean);if(response.found)return response}if(country==="SK"&&slovakDic){const response=await attachSlovakFinancials(emptyResponse(""),slovakDic,"dic");response.warnings=response.warnings.filter(Boolean);if(response.found)return response}if(country==="SK"&&!slovakIco&&!slovakDic&&query.length>=3){const resolvedIco=await resolveSlovakName(query);if(resolvedIco){const response=await attachSlovakFinancials(emptyResponse(""),resolvedIco,"ico");response.warnings=response.warnings.filter(Boolean);if(response.found)return response}return emptyResponse("Nessuna società slovacca verificabile nel Registro slovacco dei bilanci. Controlla ragione sociale, IČO o DIČ.")}if(country==="GR"&&/^\d{10}$/.test(normalized)){const direct=await browserRegistryResponse("GR",normalized,query);if(direct)return direct}if(country==="LU"&&/^B\d+$/.test(normalized)){const direct=await browserRegistryResponse("LU",normalized,query);if(direct)return direct}let effectiveVat=vat,polishResolution:PolishKrsResolution|undefined;if(country==="PL"&&query.length>=3&&!normalized){polishResolution=await resolvePolishKrsByName(query);if(polishResolution.krs)effectiveVat=`PL${polishResolution.krs}`}const{runSearch}=await import("./company-finder/orchestrator");try{const response=await runSearch({query,vat:effectiveVat,country});if(country==="PL"){const krs=(response.company?.registry?.id??polishResolution?.krs??normalized).replace(/\D/g,"");const esefAttached=await attachPolishEsefFinancials(response,query);if(/^\d{8}$|^\d{10}$/.test(krs)){const page=officialPageFor("PL",krs,response.company?.name?.trim()||query);if(page&&!esefAttached)response.officialPage=page}if(polishResolution)response.warnings=[polishResolution.detail??"Risoluzione KRS effettuata tramite GLEIF",...response.warnings]}if(country==="NO")await attachNorwayFinancials(response,normalized);return prioritizeBalanceDocument(response,normalized||polishResolution?.krs||"")}catch(error){console.error("[company-finder] errore orchestratore",error);return emptyResponse("Errore interno durante la consultazione delle fonti. Riprova tra qualche istante.")}});