export interface Source { domain:string; name:string; country:string }
export const WHITELIST:Source[]=[
{domain:'oecd.org',name:'OECD',country:'INT'},{domain:'oecd-ilibrary.org',name:'OECD iLibrary',country:'INT'},
{domain:'ec.europa.eu',name:'European Commission',country:'EU'},{domain:'agenziaentrate.gov.it',name:'Agenzia delle Entrate',country:'IT'},
{domain:'mef.gov.it',name:'MEF',country:'IT'},{domain:'normattiva.it',name:'Normattiva',country:'IT'},
{domain:'incometaxindia.gov.in',name:'CBDT India',country:'IN'},{domain:'gov.uk',name:'HMRC / UK Government',country:'UK'},
{domain:'irs.gov',name:'IRS',country:'US'},{domain:'ato.gov.au',name:'ATO Australia',country:'AU'},
{domain:'cra-arc.gc.ca',name:'CRA Canada',country:'CA'},{domain:'bfd.de',name:'Bundesfinanzdirektion',country:'DE'},
{domain:'finances.gouv.fr',name:'DGFiP France',country:'FR'},
{domain:'finance.belgium.be',name:'Federal Public Service Finance',country:'BE'},
{domain:'bundesfinanzministerium.de',name:'Bundesministerium der Finanzen',country:'DE'},
{domain:'mof.gov.cy',name:'Tax Department Cipro',country:'CY'},
{domain:'hasil.gov.my',name:'Inland Revenue Board of Malaysia',country:'MY'},
{domain:'rijksoverheid.nl',name:'Ministerie van Financien',country:'NL'},
{domain:'eur-lex.europa.eu',name:'EUR-Lex (UE)',country:'EU'},
{domain:'finance.ec.europa.eu',name:'European Commission Finance',country:'EU'},
{domain:'taxation-customs.ec.europa.eu',name:'EU Taxation & Customs',country:'EU'},
{domain:'gdt.gov.vn',name:'General Dept of Taxation Vietnam',country:'VN'},
{domain:'infocuria.curia.europa.eu',name:'CURIA (Corte UE)',country:'EU'},
{domain:'mfinante.gov.ro',name:'Ministerul Finantelor Romania',country:'RO'},
{domain:'sii.cl',name:'Servicio de Impuestos Internos Chile',country:'CL'},
{domain:'impuestos.gob.bo',name:'SIN Bolivia',country:'BO'},
{domain:'sunat.gob.pe',name:'SUNAT Peru',country:'PE'},
{domain:'sars.gov.za',name:'SARS South Africa',country:'ZA'},
{domain:'rra.gov.rw',name:'RRA Rwanda',country:'RW'},
{domain:'mif.gov.me',name:'MIF Montenegro',country:'ME'},
{domain:'iras.gov.sg',name:'IRAS Singapore',country:'SG'},
{domain:'impots.gouv.fr',name:'DGFiP France',country:'FR'},
{domain:'canada.ca',name:'Government of Canada',country:'CA'},
{domain:'nts.go.kr',name:'NTS Korea',country:'KR'},
{domain:'nav.gov.hu',name:'NAV Hungary',country:'HU'},
{domain:'nalog.gov.ru',name:'FTS Russia',country:'RU'},
{domain:'mra.mw',name:'MRA Malawi',country:'MW'},
{domain:'mof.gov.tw',name:'MOF Taiwan',country:'TW'},
{domain:'mof.gov.kw',name:'MOF Kuwait',country:'KW'},
{domain:'nbr.gov.bh',name:'NBR Bahrain',country:'BH'},
{domain:'cfr.gov.mt',name:'CFR Malta',country:'MT'},
{domain:'purs.gov.rs',name:'PURS Serbia',country:'RS'},
{domain:'nta.go.jp',name:'NTA Japan',country:'JP'},
{domain:'ird.govt.nz',name:'IRD New Zealand',country:'NZ'},
{domain:'tax.gov.ae',name:'FTA UAE',country:'AE'},
{domain:'gov.br',name:'Receita Federal Brazil',country:'BR'},
{domain:'dgi.gob.pa',name:'DGI Panama',country:'PA'},
{domain:'arca.gob.ar',name:'ARCA Argentina',country:'AR'},
{domain:'vmi.lt',name:'VMI Lithuania',country:'LT'},
{domain:'dian.gov.co',name:'DIAN Colombia',country:'CO'},
{domain:'fisc.md',name:'STS Moldova',country:'MD'},
{domain:'impotsdirects.public.lu',name:'ACD Luxembourg',country:'LU'},
{domain:'mfdgi.gov.dz',name:'MFDGI Algeria',country:'DZ'},
{domain:'kra.go.ke',name:'KRA Kenya',country:'KE'},
{domain:'belastingdienst.nl',name:'Belastingdienst Netherlands',country:'NL'},
{domain:'hmrc.gov.uk',name:'HMRC UK',country:'UK'},
{domain:'gov.pl',name:'Government of Poland',country:'PL'}
];
export function extractDomain(url:string){try{return new URL(url).hostname.toLowerCase().replace(/^www\./,'')}catch{return ''}}
export function findSource(domain:string){const d=domain.toLowerCase().replace(/^www\./,'');return WHITELIST.find(s=>d===s.domain||d.endsWith(`.${s.domain}`))??null}
export function isAllowedHost(domain:string){return findSource(domain)!==null}
export function canonicalUrl(url:string){try{const u=new URL(url);u.hash='';for(const k of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content'])u.searchParams.delete(k);u.pathname=u.pathname.replace(/\/+$/,'')||'/';return u.toString().toLowerCase()}catch{return url.trim().toLowerCase()}}