import type { CountryInfo, Financials } from "../../types";
import { numericRegistryId, searchGleif } from "../gleif";

const BASE_URL = "https://www.registeruz.sk/cruz-public";
const DEFAULT_TIMEOUT_MS = 20_000;
const SOURCE = "Registro slovacco dei bilanci (Registeruz)";

export interface RuzAccountingEntity { id:number; ico:string; name:string; address?:string|undefined; statementIds:number[]; legalForm?:string|undefined; status?:string|undefined; registeredSince?:string|undefined; }
export interface RuzStatement { id:number; periodEnd?:string|undefined; filingDate?:string|undefined; type?:string|undefined; reportIds:number[]; }
export interface RuzAttachment { id:number; name:string; mimeType:string; }
export interface RuzReport { id:number; attachments:RuzAttachment[]; }
export interface RuzCompanyResult { company:RuzAccountingEntity; financials:Financials; }
export interface RuzProviderResult { ok:boolean; data?:RuzCompanyResult; error?:string; }

function isNumericId(value:unknown):value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= 0 && value <= 9_999_999_999; }
export function normalizeRuzIco(value:string):string|undefined { const digits=value.replace(/\D/g,""); return /^\d{8}$/.test(digits)?digits:undefined; }
export function normalizeRuzDic(value:string):string|undefined { const digits=value.replace(/\D/g,""); return /^\d{10}$/.test(digits)?digits:undefined; }
export async function resolveRuzIcoByName(name:string,timeoutMs=10_000):Promise<string|undefined> { const result=await searchGleif(name,"SK",timeoutMs); if(!result.ok)return undefined; for(const match of result.matches){ if(match.country!=="SK")continue; const ico=normalizeRuzIco(numericRegistryId(match.registeredAs)??""); if(ico)return ico; } return undefined; }
export function buildRuzAttachmentUrl(id:number):string { if(!isNumericId(id))throw new Error("attachment id RÚZ non valido"); return `${BASE_URL}/domain/financialreport/attachment/${id}`; }
export function parseRuzAccountingEntity(value:unknown):RuzAccountingEntity { if(!value||typeof value!=="object")throw new Error("RÚZ accounting entity non valida"); const raw=value as Record<string,unknown>; if(!isNumericId(raw["id"])||typeof raw["ico"]!=="string"||typeof raw["nazovUJ"]!=="string")throw new Error("RÚZ accounting entity incompleta"); const statementIds=Array.isArray(raw["idUctovnychZavierok"])?raw["idUctovnychZavierok"].filter(isNumericId):[]; const address=[raw["ulica"],raw["psc"],raw["mesto"]].filter((x):x is string=>typeof x==="string"&&x.trim().length>0).join(", "); return {id:raw["id"],ico:raw["ico"],name:raw["nazovUJ"],address:address||undefined,statementIds,legalForm:typeof raw["pravnaForma"]==="string"?raw["pravnaForma"]:undefined,registeredSince:typeof raw["datumZalozenia"]==="string"?raw["datumZalozenia"]:undefined,status:typeof raw["datumZrusenia"]==="string"?`Cessata ${raw["datumZrusenia"]}`:"Attiva"}; }
export function parseRuzFinancialStatement(value:unknown):RuzStatement { if(!value||typeof value!=="object")throw new Error("RÚZ financial statement non valida"); const raw=value as Record<string,unknown>; if(!isNumericId(raw["id"]))throw new Error("RÚZ financial statement senza id"); return {id:raw["id"],periodEnd:typeof raw["obdobieDo"]==="string"?raw["obdobieDo"]:undefined,filingDate:typeof raw["datumPodania"]==="string"?raw["datumPodania"]:undefined,type:typeof raw["typ"]==="string"?raw["typ"]:undefined,reportIds:Array.isArray(raw["idUctovnychVykazov"])?raw["idUctovnychVykazov"].filter(isNumericId):[]}; }
export function parseRuzReport(value:unknown):RuzReport { if(!value||typeof value!=="object")throw new Error("RÚZ report non valido"); const raw=value as Record<string,unknown>; if(!isNumericId(raw["id"]))throw new Error("RÚZ report senza id"); const attachments=Array.isArray(raw["prilohy"])?raw["prilohy"].flatMap(item=>{if(!item||typeof item!=="object")return[];const a=item as Record<string,unknown>;if(!isNumericId(a["id"])||typeof a["meno"]!=="string")return[];const mimeType=typeof a["mimeType"]==="string"?a["mimeType"]:"";return mimeType.toLowerCase().includes("pdf")||a["meno"].toLowerCase().endsWith(".pdf")?[{id:a["id"],name:a["meno"],mimeType:mimeType||"application/pdf"}]:[];}):[]; return {id:raw["id"],attachments}; }
function yearOf(value?:string):number|undefined { const match=value?.match(/^(20\d{2})-/); return match?Number(match[1]):undefined; }
function internalAttachmentUrl(id:number):string { return `/api/company-finder/ruz-document?attachment=${id}&download=1`; }
async function ruzFetch<T>(path:string,signal:AbortSignal):Promise<T>{ const response=await fetch(`${BASE_URL}${path}`,{method:"GET",headers:{Accept:"application/json","User-Agent":"TPBox-Company-Finder/1.0"},signal,cache:"no-store"}); if(!response.ok)throw new Error(`RÚZ HTTP ${response.status}`); try{return await response.json() as T;}catch{throw new Error("RÚZ ha restituito JSON non valido");} }
async function fetchRuzCompanyByIdentifier(parameter:"ico"|"dic",identifier:string,timeoutMs=DEFAULT_TIMEOUT_MS):Promise<RuzProviderResult>{ const normalized=parameter==="ico"?normalizeRuzIco(identifier):normalizeRuzDic(identifier); if(!normalized)return{ok:false,error:parameter==="ico"?"IČO slovacco non valido: servono otto cifre":"DIČ slovacco non valido: servono dieci cifre"}; const controller=new AbortController(); const timer=setTimeout(()=>controller.abort(),timeoutMs); try { const index=await ruzFetch<{id?:unknown[]}>(`/api/uctovne-jednotky?zmenene-od=2000-01-01&${parameter}=${encodeURIComponent(normalized)}&max-zaznamov=100`,controller.signal); const candidateId=Array.isArray(index.id)?index.id.find(isNumericId):undefined; if(candidateId===undefined)return{ok:true,data:{company:{id:0,ico:parameter==="ico"?normalized:"",name:"",statementIds:[]},financials:{available:false,years:[],source:SOURCE,documents:[]}}}; const company=parseRuzAccountingEntity(await ruzFetch(`/api/uctovna-jednotka?id=${candidateId}`,controller.signal)); const statements=await Promise.all(company.statementIds.slice(0,30).map(async id=>parseRuzFinancialStatement(await ruzFetch(`/api/uctovna-zavierka?id=${id}`,controller.signal)))); const reportIds=[...new Set(statements.flatMap(s=>s.reportIds))].slice(0,60); const reports=await Promise.all(reportIds.map(async id=>parseRuzReport(await ruzFetch(`/api/uctovny-vykaz?id=${id}`,controller.signal)))); const statementByReport=new Map<number,RuzStatement>(); for(const statement of statements)for(const reportId of statement.reportIds)statementByReport.set(reportId,statement); const documents=reports.flatMap(report=>{const statement=statementByReport.get(report.id);const year=yearOf(statement?.periodEnd);return report.attachments.map(attachment=>({id:`SK-${company.ico}-${year??"unknown"}-${attachment.id}`,year,kind:"ANNUAL_REPORT" as const,format:"pdf" as const,availability:"DOCUMENT_DOWNLOADABLE" as const,title:attachment.name,downloadUrl:internalAttachmentUrl(attachment.id)}));}); const years=[...new Set(documents.map(d=>d.year).filter((y):y is number=>y!==undefined))].sort((a,b)=>b-a); return{ok:true,data:{company,financials:{available:documents.length>0,years:years.map(year=>({periodLabel:String(year),year,currency:"EUR"})),source:SOURCE,note:"Documenti pubblici RÚZ recuperati server-side.",documents}}}; }catch(error){const err=error as{name?:string;message?:string};return{ok:false,error:err?.name==="AbortError"?"RÚZ timeout":err?.message??"RÚZ non disponibile"};}finally{clearTimeout(timer);} }
export function fetchRuzCompanyByIco(input:string,timeoutMs=DEFAULT_TIMEOUT_MS):Promise<RuzProviderResult>{return fetchRuzCompanyByIdentifier("ico",input,timeoutMs);}
export function fetchRuzCompanyByDic(input:string,timeoutMs=DEFAULT_TIMEOUT_MS):Promise<RuzProviderResult>{return fetchRuzCompanyByIdentifier("dic",input,timeoutMs);}
