import type { PatentRecord } from "./types";

/**
 * Indice dimostrativo. Sostituibile senza modifiche alla UI: l'adapter
 * server-side scrive nello stesso formato dopo la revisione editoriale.
 */
export const PATENT_DEMO_INDEX: readonly PatentRecord[] = [
  {
    id: "wo-2023-114872",
    publicationNumber: "WO/2023/114872",
    title: "Sistema di ottimizzazione predittiva per reti logistiche multi-nodo",
    abstract:
      "Metodo per l'allocazione dinamica di capacità in reti distributive, con modello previsionale addestrato su serie storiche di domanda.",
    applicants: ["Alfa Industrial Holding S.A."],
    inventors: ["M. Rossi", "L. Beringer"],
    ipcCodes: ["G06Q 10/08", "G06N 20/00"],
    filingDate: "2021-12-14",
    publicationDate: "2023-06-22",
    jurisdictions: ["WO", "EP", "US", "IT"],
    familySize: 7,
    technologyArea: "Software e AI",
    tpRelevance:
      "Titolarità in holding lussemburghese con R&D svolta in Italia: verificare allineamento DEMPE e remunerazione delle funzioni di sviluppo.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2023114872",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2022-201455",
    publicationNumber: "WO/2022/201455",
    title: "Formulazione polimerica biodegradabile per imballaggi alimentari",
    abstract:
      "Composizione a base di poliesteri di origine vegetale con barriera all'ossigeno migliorata e processo di estrusione a bassa temperatura.",
    applicants: ["Beta Materials S.p.A."],
    inventors: ["G. Ferrari", "S. Okafor"],
    ipcCodes: ["C08L 67/04", "B65D 65/46"],
    filingDate: "2021-03-19",
    publicationDate: "2022-09-29",
    jurisdictions: ["WO", "EP", "CN"],
    familySize: 5,
    technologyArea: "Chimica e materiali",
    tpRelevance:
      "Brevetto detenuto dall'entità produttiva italiana: possibile royalty in uscita verso consociate distributive.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2022201455",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2024-018903",
    publicationNumber: "WO/2024/018903",
    title: "Dispositivo indossabile per il monitoraggio continuo della glicemia",
    abstract:
      "Sensore ottico non invasivo con algoritmo di calibrazione adattiva e trasmissione cifrata verso applicazione mobile.",
    applicants: ["Gamma Medtech Ltd."],
    inventors: ["A. Petrova", "J. Lindqvist"],
    ipcCodes: ["A61B 5/145", "G16H 40/67"],
    filingDate: "2022-07-21",
    publicationDate: "2024-01-25",
    jurisdictions: ["WO", "US", "JP", "EP"],
    familySize: 9,
    technologyArea: "Life science e dispositivi medici",
    tpRelevance:
      "Intangibile maturo con famiglia ampia: valutare metodo di ripartizione dei profitti tra sviluppo e commercializzazione.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2024018903",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2021-155320",
    publicationNumber: "WO/2021/155320",
    title: "Metodo di riciclo chimico di batterie agli ioni di litio",
    abstract:
      "Processo idrometallurgico per il recupero selettivo di litio, cobalto e nichel da celle esauste con riduzione dei reflui acidi.",
    applicants: ["Delta Circular Energy GmbH", "Epsilon Research Foundation"],
    inventors: ["T. Bauer"],
    ipcCodes: ["H01M 10/54", "C22B 7/00"],
    filingDate: "2020-01-30",
    publicationDate: "2021-08-12",
    jurisdictions: ["WO", "EP", "KR"],
    familySize: 4,
    technologyArea: "Energia e ambiente",
    tpRelevance:
      "Co-titolarità tra impresa e fondazione di ricerca: verificare accordi di cost contribution arrangement.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2021155320",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2023-047781",
    publicationNumber: "WO/2023/047781",
    title: "Architettura di pagamento tokenizzato con verifica off-chain",
    abstract:
      "Sistema per l'autorizzazione di transazioni tramite token effimeri e registro distribuito permissioned.",
    applicants: ["Zeta Payments Holding B.V."],
    inventors: ["R. de Vries", "N. Haddad"],
    ipcCodes: ["G06Q 20/38", "H04L 9/32"],
    filingDate: "2021-09-24",
    publicationDate: "2023-03-30",
    jurisdictions: ["WO", "US", "SG"],
    familySize: 6,
    technologyArea: "Software e AI",
    tpRelevance:
      "IP in holding olandese con sviluppo distribuito: attenzione alla sostanza delle funzioni di controllo del rischio.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2023047781",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2020-098211",
    publicationNumber: "WO/2020/098211",
    title: "Turbina eolica ad asse verticale con pale a geometria variabile",
    abstract:
      "Rotore con attuatori che modificano l'incidenza delle pale in funzione della velocità del vento per ridurre i carichi strutturali.",
    applicants: ["Eta Wind Systems S.L."],
    inventors: ["C. Muñoz"],
    ipcCodes: ["F03D 3/06"],
    filingDate: "2018-11-12",
    publicationDate: "2020-05-22",
    jurisdictions: ["WO", "EP"],
    familySize: 3,
    technologyArea: "Energia e ambiente",
    tpRelevance:
      "Portafoglio limitato e in fase avanzata di vita utile: rilevante per test di impairment e revisione delle royalty.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2020098211",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2024-133090",
    publicationNumber: "WO/2024/133090",
    title: "Processo di sintesi enzimatica di intermedi farmaceutici chirali",
    abstract:
      "Biocatalisi in flusso continuo con enzima immobilizzato e recupero del solvente, con resa enantiomerica superiore al 98%.",
    applicants: ["Theta Pharma S.p.A."],
    inventors: ["F. Colombo", "H. Nakamura"],
    ipcCodes: ["C12P 41/00", "C07D 213/00"],
    filingDate: "2022-12-19",
    publicationDate: "2024-06-27",
    jurisdictions: ["WO", "EP", "US", "IN"],
    familySize: 8,
    technologyArea: "Life science e dispositivi medici",
    tpRelevance:
      "Know-how di processo non brevettato accanto al brevetto: valutare la componente di trade secret nella base di remunerazione.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2024133090",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2022-076544",
    publicationNumber: "WO/2022/076544",
    title: "Sistema di visione artificiale per il controllo qualità in linea",
    abstract:
      "Ispezione ottica con rete neurale convoluzionale addestrata su difetti superficiali e retroazione sui parametri di processo.",
    applicants: ["Iota Automation S.r.l."],
    inventors: ["P. Greco"],
    ipcCodes: ["G06T 7/00", "G01N 21/88"],
    filingDate: "2020-10-08",
    publicationDate: "2022-04-14",
    jurisdictions: ["WO", "EP", "IT"],
    familySize: 4,
    technologyArea: "Meccanica e automazione",
    tpRelevance:
      "IP sviluppato e detenuto in Italia da PMI del gruppo: verificare la congruità dei servizi resi alle consociate.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2022076544",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2023-190228",
    publicationNumber: "WO/2023/190228",
    title: "Piattaforma di telemetria per flotte di veicoli elettrici",
    abstract:
      "Aggregazione di dati di ricarica e consumo con modelli di previsione dell'autonomia residua e pianificazione delle soste.",
    applicants: ["Kappa Mobility Holding S.A."],
    inventors: ["D. Novak", "E. Silva"],
    ipcCodes: ["G07C 5/00", "B60L 58/12"],
    filingDate: "2022-03-31",
    publicationDate: "2023-10-05",
    jurisdictions: ["WO", "EP", "BR"],
    familySize: 5,
    technologyArea: "Meccanica e automazione",
    tpRelevance:
      "Piattaforma usata da più entità del gruppo: candidato tipico a licenza infragruppo o servizio centralizzato.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2023190228",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2021-233077",
    publicationNumber: "WO/2021/233077",
    title: "Tessuto tecnico a rilascio controllato di principi attivi",
    abstract:
      "Filato incapsulante microcapsule con rilascio attivato dall'attrito, destinato ad abbigliamento tecnico e dispositivi sanitari.",
    applicants: ["Lambda Textiles S.p.A."],
    inventors: ["V. Marchetti"],
    ipcCodes: ["D01F 1/10", "A61L 15/44"],
    filingDate: "2020-05-18",
    publicationDate: "2021-11-25",
    jurisdictions: ["WO", "EP", "TR"],
    familySize: 3,
    technologyArea: "Chimica e materiali",
    tpRelevance:
      "Marchio e brevetto detenuti da entità diverse: verificare la separazione dei flussi di royalty.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2021233077",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2024-071455",
    publicationNumber: "WO/2024/071455",
    title: "Metodo di compressione di modelli linguistici per inferenza locale",
    abstract:
      "Quantizzazione mista con distillazione selettiva degli strati di attenzione per l'esecuzione su dispositivi a risorse limitate.",
    applicants: ["Mu Cognitive Labs Inc."],
    inventors: ["Y. Chen", "K. Adeyemi"],
    ipcCodes: ["G06N 3/0495", "G06F 9/50"],
    filingDate: "2022-09-28",
    publicationDate: "2024-04-04",
    jurisdictions: ["WO", "US", "EP", "KR"],
    familySize: 10,
    technologyArea: "Software e AI",
    tpRelevance:
      "Intangibile ad alto valore in fase iniziale: rilevante per hard-to-value intangibles e clausole di price adjustment.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2024071455",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
  {
    id: "wo-2020-172366",
    publicationNumber: "WO/2020/172366",
    title: "Impianto modulare per la potabilizzazione decentralizzata",
    abstract:
      "Unità containerizzata con ultrafiltrazione e disinfezione UV, telecontrollata e dimensionata per piccole comunità.",
    applicants: ["Nu Water Solutions AG"],
    inventors: ["B. Keller"],
    ipcCodes: ["C02F 1/32", "B01D 61/14"],
    filingDate: "2019-02-20",
    publicationDate: "2020-08-27",
    jurisdictions: ["WO", "EP", "ZA"],
    familySize: 3,
    technologyArea: "Energia e ambiente",
    tpRelevance:
      "Deposito in giurisdizioni emergenti: utile per mappare i mercati serviti e la localizzazione dei rischi.",
    sourceName: "WIPO PATENTSCOPE",
    officialUrl: "https://patentscope.wipo.int/search/en/detail.jsf?docId=WO2020172366",
    dataOrigin: "DEMO",
    lastVerifiedAt: "2026-07-30",
  },
];