import type {
  CompanyCandidate,
  FinancialYear,
  NewsItem,
  NewsSource,
} from "./types";

/**
 * Configurazione fonti (solo metadati sintetici, nessun contenuto reale scaricato).
 * RSS ammesso solo se verificato: nessuna fonte è oggi in modalità RSS.
 */
export const DEMO_SOURCES: NewsSource[] = [
  {
    id: "oecd-tp",
    name: "OECD Transfer Pricing",
    acquisitionMode: "HTML_WATCH",
    tier: "PRIMARY",
    kind: "ISTITUZIONALE",
    feedUrl: null,
    siteUrl: "https://www.oecd.org/tax/transfer-pricing/",
    geo: "OCSE",
    note: "Feed non verificato: monitoraggio pagina istituzionale lato server.",
  },
  {
    id: "ec-taxud-news",
    name: "European Commission — Taxation and Customs News",
    acquisitionMode: "HTML_WATCH",
    tier: "PRIMARY",
    kind: "ISTITUZIONALE",
    feedUrl: null,
    siteUrl: "https://taxation-customs.ec.europa.eu/news_en",
    geo: "UE",
    note: "Feed non verificato: monitoraggio pagina istituzionale lato server.",
  },
  {
    id: "mnetax-tp",
    name: "MNE Tax — Transfer Pricing",
    acquisitionMode: "HTML_WATCH",
    tier: "SECONDARY",
    kind: "PROFESSIONALE",
    feedUrl: null,
    siteUrl: "https://mnetax.com/category/transfer-pricing",
    geo: "GLOBALE",
    note: "Fonte secondaria: solo segnalazione, verifica sempre sulla fonte primaria.",
  },
  {
    id: "kluwer-itax-blog",
    name: "Kluwer International Tax Blog",
    acquisitionMode: "HTML_WATCH",
    tier: "SECONDARY",
    kind: "PROFESSIONALE",
    feedUrl: null,
    siteUrl: "http://kluwertaxblog.com/",
    geo: "GLOBALE",
    note: "Fonte secondaria: commento dottrinale, non prassi ufficiale.",
  },
  {
    id: "wu-learn-news",
    name: "WU LEARN — general news",
    acquisitionMode: "DISABLED",
    tier: "SECONDARY",
    kind: "ACCADEMICA",
    feedUrl: null,
    siteUrl: "https://www.wu.ac.at/en/",
    geo: "GLOBALE",
    note: "Acquisizione disattivata: rilevanza Transfer Pricing non selettiva.",
  },
];

export const DEMO_NEWS: NewsItem[] = [
  {
    id: "n-2026-0142",
    title:
      "Aggiornamento delle linee guida OCSE sui metodi di determinazione dei prezzi di trasferimento",
        summary:
      "La segreteria pubblica un pacchetto di chiarimenti sull'applicazione del metodo del margine netto della transazione nelle catene di distribuzione a rischio limitato, con esempi numerici aggiuntivi.",
    sourceId: "oecd-tp",
    sourceName: "OECD Transfer Pricing",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-07-28",
    lastVerifiedAt: "2026-08-04T07:20:00Z",
    language: "en",
    geo: "OCSE",
    topic: "Metodi e comparabili",
    originalUrl: "https://www.oecd.org/tax/transfer-pricing/",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0141",
    title:
      "Commissione europea: consultazione pubblica sulla semplificazione degli oneri documentali infragruppo",
    summary:
      "Apertura di una consultazione rivolta a imprese e professionisti sulla standardizzazione del Master File nel mercato interno e sull'interazione con le regole di allocazione dei profitti.",
    sourceId: "ec-taxud-news",
    sourceName: "European Commission — Taxation and Customs News",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-07-24",
    lastVerifiedAt: "2026-08-04T07:20:00Z",
    language: "en",
    geo: "UE",
    topic: "Documentazione",
    originalUrl: "https://taxation-customs.ec.europa.eu/news_en",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0140",
    title:
      "Pillar Two: chiarimenti amministrativi sull'interazione tra safe harbour transitori e rettifiche di transfer pricing",
    summary:
      "Nota di prassi sul trattamento delle rettifiche di fine esercizio ai fini del calcolo dell'aliquota effettiva d'imposta e sui riflessi sui test dei safe harbour.",
    sourceId: "oecd-tp",
    sourceName: "OECD Transfer Pricing",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-07-18",
    lastVerifiedAt: "2026-08-03T06:05:00Z",
    language: "en",
    geo: "OCSE",
    topic: "Pillar Two",
    originalUrl: "https://www.oecd.org/tax/transfer-pricing/",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0139",
    title:
      "Italia: aggiornamento della prassi sugli accordi preventivi per le imprese con attività internazionale",
    summary:
      "Indicazioni operative sulla fase di ammissibilità delle istanze di accordo preventivo e sui contenuti minimi dell'analisi funzionale allegata.",
    sourceId: "ec-taxud-news",
    sourceName: "European Commission — Taxation and Customs News",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-07-11",
    lastVerifiedAt: "2026-08-01T06:40:00Z",
    language: "it",
    geo: "ITALIA",
    topic: "APA e MAP",
    originalUrl: "https://taxation-customs.ec.europa.eu/news_en",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0138",
    title:
      "Analisi: la valorizzazione degli intangibili di marketing nelle strutture di distribuzione europee",
    summary:
      "Contributo professionale sulle recenti tendenze di controllo in materia di remunerazione dei distributori che sostengono spese pubblicitarie significative.",
    sourceId: "mnetax-tp",
    sourceName: "MNE Tax — Transfer Pricing",
    sourceKind: "PROFESSIONALE",
    sourceTier: "SECONDARY",
    originalDate: "2026-07-08",
    lastVerifiedAt: "2026-07-30T09:10:00Z",
    language: "en",
    geo: "GLOBALE",
    topic: "Intangibili",
    originalUrl: "https://mnetax.com/category/transfer-pricing",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0137",
    title:
      "Commento: onere della prova e presunzioni nelle controversie sui servizi infragruppo",
    summary:
      "Riflessione dottrinale sull'evoluzione giurisprudenziale in tema di inerenza e beneficio dei servizi resi dalla capogruppo alle controllate.",
    sourceId: "kluwer-itax-blog",
    sourceName: "Kluwer International Tax Blog",
    sourceKind: "PROFESSIONALE",
    sourceTier: "SECONDARY",
    originalDate: "2026-06-30",
    lastVerifiedAt: "2026-07-29T08:00:00Z",
    language: "en",
    geo: "GLOBALE",
    topic: "Servizi infragruppo",
    originalUrl: "http://kluwertaxblog.com/",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0136",
    title:
      "Country Profiles: revisione delle schede nazionali su metodi ammessi e fonti normative interne",
    summary:
      "Aggiornamento delle schede paese con indicazione delle regole interne su selezione dei metodi, aggiustamenti di comparabilità e obblighi documentali.",
    sourceId: "oecd-tp",
    sourceName: "OECD Transfer Pricing",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-06-19",
    lastVerifiedAt: "2026-07-28T06:15:00Z",
    language: "en",
    geo: "OCSE",
    topic: "Metodi e comparabili",
    originalUrl: "https://www.oecd.org/tax/transfer-pricing/",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0135",
    title:
      "Contenzioso: rassegna delle pronunce nazionali su rettifiche di margine nelle vendite infragruppo",
    summary:
      "Sintesi ragionata delle decisioni di merito pubblicate nel semestre, con indicazione dei criteri di selezione dei comparabili accolti dai giudici.",
    sourceId: "mnetax-tp",
    sourceName: "MNE Tax — Transfer Pricing",
    sourceKind: "PROFESSIONALE",
    sourceTier: "SECONDARY",
    originalDate: "2026-06-05",
    lastVerifiedAt: "2026-07-26T10:30:00Z",
    language: "en",
    geo: "GLOBALE",
    topic: "Contenzioso",
    originalUrl: "https://mnetax.com/category/transfer-pricing",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0134",
    title:
      "Unione europea: stato di avanzamento dei lavori sul coordinamento delle rettifiche corrispondenti",
    summary:
      "Nota informativa sull'attività dei gruppi tecnici in materia di eliminazione della doppia imposizione economica derivante da rettifiche primarie.",
    sourceId: "ec-taxud-news",
    sourceName: "European Commission — Taxation and Customs News",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-05-22",
    lastVerifiedAt: "2026-07-20T07:45:00Z",
    language: "fr",
    geo: "UE",
    topic: "APA e MAP",
    originalUrl: "https://taxation-customs.ec.europa.eu/news_en",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0133",
    title:
      "Documentazione: criteri sintetici per la selezione del set di comparabili nelle analisi di benchmark",
    summary:
      "Approfondimento metodologico su filtri quantitativi e qualitativi, trattamento delle perdite ricorrenti e motivazione degli scarti.",
    sourceId: "kluwer-itax-blog",
    sourceName: "Kluwer International Tax Blog",
    sourceKind: "PROFESSIONALE",
    sourceTier: "SECONDARY",
    originalDate: "2026-05-09",
    lastVerifiedAt: "2026-07-18T08:20:00Z",
    language: "en",
    geo: "GLOBALE",
    topic: "Documentazione",
    originalUrl: "http://kluwertaxblog.com/",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
  {
    id: "n-2026-0132",
    title:
      "Italia: nota di sintesi sugli obblighi documentali e sul regime premiale sanzionatorio",
    summary:
      "Ricognizione degli adempimenti formali e delle tempistiche di predisposizione della documentazione idonea per i gruppi con società italiane.",
    sourceId: "ec-taxud-news",
    sourceName: "European Commission — Taxation and Customs News",
    sourceKind: "ISTITUZIONALE",
    sourceTier: "PRIMARY",
    originalDate: "2026-04-28",
    lastVerifiedAt: "2026-07-15T06:30:00Z",
    language: "it",
    geo: "ITALIA",
    topic: "Documentazione",
    originalUrl: "https://taxation-customs.ec.europa.eu/news_en",
    workflowState: "PUBLISHED",
    isDemo: true,
  },
];

/** Elementi acquisiti in attesa di revisione redazionale: mai pubblicati automaticamente. */
export const DEMO_DRAFTS_PENDING = 7;

export const DEMO_COMPANIES: CompanyCandidate[] = [
  {
    companyId: "cmp-demo-000181",
    legalName: "Alfieri Componenti Industriali S.p.A.",
    country: "IT",
    city: "Torino",
    legalForm: "Società per azioni",
    activity: "Produzione di componenti meccanici",
    lastFilingYear: 2025,
    isDemo: true,
  },
  {
    companyId: "cmp-demo-000182",
    legalName: "Alfieri Distribuzione Europa S.r.l.",
    country: "IT",
    city: "Milano",
    legalForm: "Società a responsabilità limitata",
    activity: "Distribuzione all'ingrosso",
    lastFilingYear: 2025,
    isDemo: true,
  },
  {
    companyId: "cmp-demo-000183",
    legalName: "Borgo Servizi Condivisi S.r.l.",
    country: "IT",
    city: "Bologna",
    legalForm: "Società a responsabilità limitata",
    activity: "Servizi amministrativi infragruppo",
    lastFilingYear: 2024,
    isDemo: true,
  },
  {
    companyId: "cmp-demo-000184",
    legalName: "Cedrino Licensing Holding N.V.",
    country: "NL",
    city: "Amsterdam",
    legalForm: "Naamloze vennootschap",
    activity: "Gestione di intangibili di gruppo",
    lastFilingYear: 2025,
    isDemo: true,
  },
  {
    companyId: "cmp-demo-000185",
    legalName: "Delta Manufacturing Iberia S.A.",
    country: "ES",
    city: "Barcellona",
    legalForm: "Sociedad anónima",
    activity: "Produzione su commessa",
    lastFilingYear: 2024,
    isDemo: true,
  },
];

export const DEMO_FINANCIALS: Record<string, FinancialYear[]> = {
  "cmp-demo-000181": [
    {
      year: 2025,
      revenue: 184_300_000,
      ebit: 12_900_000,
      netResult: 8_400_000,
      totalAssets: 210_500_000,
      equity: 96_200_000,
      employees: 742,
    },
    {
      year: 2024,
      revenue: 171_800_000,
      ebit: 10_600_000,
      netResult: 6_900_000,
      totalAssets: 198_100_000,
      equity: 89_400_000,
      employees: 715,
    },
    {
      year: 2023,
      revenue: 162_400_000,
      ebit: 9_100_000,
      netResult: 5_600_000,
      totalAssets: 187_900_000,
      equity: 83_100_000,
      employees: 698,
    },
  ],
};

/** Serie sintetica di fallback, usata per qualsiasi companyId risolto. */
export const DEMO_FINANCIALS_FALLBACK: FinancialYear[] = [
  {
    year: 2025,
    revenue: 47_600_000,
    ebit: 2_850_000,
    netResult: 1_740_000,
    totalAssets: 58_200_000,
    equity: 21_300_000,
    employees: 186,
  },
  {
    year: 2024,
    revenue: 44_100_000,
    ebit: 2_310_000,
    netResult: 1_380_000,
    totalAssets: 54_700_000,
    equity: 19_800_000,
    employees: 179,
  },
  {
    year: 2023,
    revenue: 41_500_000,
    ebit: 1_920_000,
    netResult: 1_050_000,
    totalAssets: 51_300_000,
    equity: 18_600_000,
    employees: 172,
  },
];