/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttualitaRouteImport } from './routes/attualita'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GiurisprudenzaRouteImport } from './routes/giurisprudenza'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NormativaRouteImport } from './routes/normativa'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AttualitaIndexRouteImport } from './routes/attualita.index'
import { Route as AttualitaAreaRouteImport } from './routes/attualita.$area'
import { Route as NormativaIndexRouteImport } from './routes/normativa.index'
import { Route as NormativaCountryProfilesRouteImport } from './routes/normativa.country-profiles'
import { Route as NormativaItaliaRouteImport } from './routes/normativa.italia'
import { Route as NormativaOcseRouteImport } from './routes/normativa.ocse'
import { Route as NormativaPillarTwoRouteImport } from './routes/normativa.pillar-two'
import { Route as NormativaUnioneEuropeaRouteImport } from './routes/normativa.unione-europea'
import { Route as ToolIndexRouteImport } from './routes/tool.index'
import { Route as ToolBilancioFinderRouteImport } from './routes/tool.bilancio-finder'
import { Route as ToolCompanyFinderRouteImport } from './routes/tool.company-finder'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as NormativaPortaleInterpelliIndexRouteImport } from './routes/normativa.portale-interpelli.index'
import { Route as NormativaPortaleInterpelliIdRouteImport } from './routes/normativa.portale-interpelli.$id'
import { Route as ToolAmountBIndexRouteImport } from './routes/tool.amount-b.index'
import { Route as ToolPortaleInterpelliIndexRouteImport } from './routes/tool.portale-interpelli.index'
import { Route as ToolPortaleInterpelliIdRouteImport } from './routes/tool.portale-interpelli.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttualitaRoute = AttualitaRouteImport.update({
  id: '/attualita',
  path: '/attualita',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GiurisprudenzaRoute = GiurisprudenzaRouteImport.update({
  id: '/giurisprudenza',
  path: '/giurisprudenza',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NormativaRoute = NormativaRouteImport.update({
  id: '/normativa',
  path: '/normativa',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttualitaIndexRoute = AttualitaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AttualitaRoute,
} as any)
const AttualitaAreaRoute = AttualitaAreaRouteImport.update({
  id: '/$area',
  path: '/$area',
  getParentRoute: () => AttualitaRoute,
} as any)
const NormativaIndexRoute = NormativaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NormativaRoute,
} as any)
const NormativaCountryProfilesRoute =
  NormativaCountryProfilesRouteImport.update({
    id: '/country-profiles',
    path: '/country-profiles',
    getParentRoute: () => NormativaRoute,
  } as any)
const NormativaItaliaRoute = NormativaItaliaRouteImport.update({
  id: '/italia',
  path: '/italia',
  getParentRoute: () => NormativaRoute,
} as any)
const NormativaOcseRoute = NormativaOcseRouteImport.update({
  id: '/ocse',
  path: '/ocse',
  getParentRoute: () => NormativaRoute,
} as any)
const NormativaPillarTwoRoute = NormativaPillarTwoRouteImport.update({
  id: '/pillar-two',
  path: '/pillar-two',
  getParentRoute: () => NormativaRoute,
} as any)
const NormativaUnioneEuropeaRoute = NormativaUnioneEuropeaRouteImport.update({
  id: '/unione-europea',
  path: '/unione-europea',
  getParentRoute: () => NormativaRoute,
} as any)
const ToolIndexRoute = ToolIndexRouteImport.update({
  id: '/tool/',
  path: '/tool/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolBilancioFinderRoute = ToolBilancioFinderRouteImport.update({
  id: '/tool/bilancio-finder',
  path: '/tool/bilancio-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolCompanyFinderRoute = ToolCompanyFinderRouteImport.update({
  id: '/tool/company-finder',
  path: '/tool/company-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const NormativaPortaleInterpelliIndexRoute =
  NormativaPortaleInterpelliIndexRouteImport.update({
    id: '/portale-interpelli/',
    path: '/portale-interpelli/',
    getParentRoute: () => NormativaRoute,
  } as any)
const NormativaPortaleInterpelliIdRoute =
  NormativaPortaleInterpelliIdRouteImport.update({
    id: '/portale-interpelli/$id',
    path: '/portale-interpelli/$id',
    getParentRoute: () => NormativaRoute,
  } as any)
const ToolAmountBIndexRoute = ToolAmountBIndexRouteImport.update({
  id: '/tool/amount-b/',
  path: '/tool/amount-b/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolPortaleInterpelliIndexRoute =
  ToolPortaleInterpelliIndexRouteImport.update({
    id: '/tool/portale-interpelli/',
    path: '/tool/portale-interpelli/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolPortaleInterpelliIdRoute = ToolPortaleInterpelliIdRouteImport.update({
  id: '/tool/portale-interpelli/$id',
  path: '/tool/portale-interpelli/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attualita': typeof AttualitaRouteWithChildren
  '/auth': typeof AuthRoute
  '/giurisprudenza': typeof GiurisprudenzaRoute
  '/mcp': typeof McpRoute
  '/normativa': typeof NormativaRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attualita/$area': typeof AttualitaAreaRoute
  '/normativa/country-profiles': typeof NormativaCountryProfilesRoute
  '/normativa/italia': typeof NormativaItaliaRoute
  '/normativa/ocse': typeof NormativaOcseRoute
  '/normativa/pillar-two': typeof NormativaPillarTwoRoute
  '/normativa/unione-europea': typeof NormativaUnioneEuropeaRoute
  '/tool/bilancio-finder': typeof ToolBilancioFinderRoute
  '/tool/company-finder': typeof ToolCompanyFinderRoute
  '/attualita/': typeof AttualitaIndexRoute
  '/normativa/': typeof NormativaIndexRoute
  '/tool/': typeof ToolIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/normativa/portale-interpelli/$id': typeof NormativaPortaleInterpelliIdRoute
  '/tool/portale-interpelli/$id': typeof ToolPortaleInterpelliIdRoute
  '/normativa/portale-interpelli/': typeof NormativaPortaleInterpelliIndexRoute
  '/tool/amount-b/': typeof ToolAmountBIndexRoute
  '/tool/portale-interpelli/': typeof ToolPortaleInterpelliIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/giurisprudenza': typeof GiurisprudenzaRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attualita/$area': typeof AttualitaAreaRoute
  '/normativa/country-profiles': typeof NormativaCountryProfilesRoute
  '/normativa/italia': typeof NormativaItaliaRoute
  '/normativa/ocse': typeof NormativaOcseRoute
  '/normativa/pillar-two': typeof NormativaPillarTwoRoute
  '/normativa/unione-europea': typeof NormativaUnioneEuropeaRoute
  '/tool/bilancio-finder': typeof ToolBilancioFinderRoute
  '/tool/company-finder': typeof ToolCompanyFinderRoute
  '/attualita': typeof AttualitaIndexRoute
  '/normativa': typeof NormativaIndexRoute
  '/tool': typeof ToolIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/normativa/portale-interpelli/$id': typeof NormativaPortaleInterpelliIdRoute
  '/tool/portale-interpelli/$id': typeof ToolPortaleInterpelliIdRoute
  '/normativa/portale-interpelli': typeof NormativaPortaleInterpelliIndexRoute
  '/tool/amount-b': typeof ToolAmountBIndexRoute
  '/tool/portale-interpelli': typeof ToolPortaleInterpelliIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attualita': typeof AttualitaRouteWithChildren
  '/auth': typeof AuthRoute
  '/giurisprudenza': typeof GiurisprudenzaRoute
  '/mcp': typeof McpRoute
  '/normativa': typeof NormativaRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/attualita/$area': typeof AttualitaAreaRoute
  '/normativa/country-profiles': typeof NormativaCountryProfilesRoute
  '/normativa/italia': typeof NormativaItaliaRoute
  '/normativa/ocse': typeof NormativaOcseRoute
  '/normativa/pillar-two': typeof NormativaPillarTwoRoute
  '/normativa/unione-europea': typeof NormativaUnioneEuropeaRoute
  '/tool/bilancio-finder': typeof ToolBilancioFinderRoute
  '/tool/company-finder': typeof ToolCompanyFinderRoute
  '/attualita/': typeof AttualitaIndexRoute
  '/normativa/': typeof NormativaIndexRoute
  '/tool/': typeof ToolIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/normativa/portale-interpelli/$id': typeof NormativaPortaleInterpelliIdRoute
  '/tool/portale-interpelli/$id': typeof ToolPortaleInterpelliIdRoute
  '/normativa/portale-interpelli/': typeof NormativaPortaleInterpelliIndexRoute
  '/tool/amount-b/': typeof ToolAmountBIndexRoute
  '/tool/portale-interpelli/': typeof ToolPortaleInterpelliIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attualita'
    | '/auth'
    | '/giurisprudenza'
    | '/mcp'
    | '/normativa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attualita/$area'
    | '/normativa/country-profiles'
    | '/normativa/italia'
    | '/normativa/ocse'
    | '/normativa/pillar-two'
    | '/normativa/unione-europea'
    | '/tool/bilancio-finder'
    | '/tool/company-finder'
    | '/attualita/'
    | '/normativa/'
    | '/tool/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/normativa/portale-interpelli/$id'
    | '/tool/portale-interpelli/$id'
    | '/normativa/portale-interpelli/'
    | '/tool/amount-b/'
    | '/tool/portale-interpelli/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/giurisprudenza'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attualita/$area'
    | '/normativa/country-profiles'
    | '/normativa/italia'
    | '/normativa/ocse'
    | '/normativa/pillar-two'
    | '/normativa/unione-europea'
    | '/tool/bilancio-finder'
    | '/tool/company-finder'
    | '/attualita'
    | '/normativa'
    | '/tool'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/normativa/portale-interpelli/$id'
    | '/tool/portale-interpelli/$id'
    | '/normativa/portale-interpelli'
    | '/tool/amount-b'
    | '/tool/portale-interpelli'
  id:
    | '__root__'
    | '/'
    | '/attualita'
    | '/auth'
    | '/giurisprudenza'
    | '/mcp'
    | '/normativa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/attualita/$area'
    | '/normativa/country-profiles'
    | '/normativa/italia'
    | '/normativa/ocse'
    | '/normativa/pillar-two'
    | '/normativa/unione-europea'
    | '/tool/bilancio-finder'
    | '/tool/company-finder'
    | '/attualita/'
    | '/normativa/'
    | '/tool/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/normativa/portale-interpelli/$id'
    | '/tool/portale-interpelli/$id'
    | '/normativa/portale-interpelli/'
    | '/tool/amount-b/'
    | '/tool/portale-interpelli/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttualitaRoute: typeof AttualitaRouteWithChildren
  AuthRoute: typeof AuthRoute
  GiurisprudenzaRoute: typeof GiurisprudenzaRoute
  McpRoute: typeof McpRoute
  NormativaRoute: typeof NormativaRouteWithChildren
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ToolBilancioFinderRoute: typeof ToolBilancioFinderRoute
  ToolCompanyFinderRoute: typeof ToolCompanyFinderRoute
  ToolIndexRoute: typeof ToolIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ToolPortaleInterpelliIdRoute: typeof ToolPortaleInterpelliIdRoute
  ToolAmountBIndexRoute: typeof ToolAmountBIndexRoute
  ToolPortaleInterpelliIndexRoute: typeof ToolPortaleInterpelliIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attualita': {
      id: '/attualita'
      path: '/attualita'
      fullPath: '/attualita'
      preLoaderRoute: typeof AttualitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giurisprudenza': {
      id: '/giurisprudenza'
      path: '/giurisprudenza'
      fullPath: '/giurisprudenza'
      preLoaderRoute: typeof GiurisprudenzaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normativa': {
      id: '/normativa'
      path: '/normativa'
      fullPath: '/normativa'
      preLoaderRoute: typeof NormativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attualita/': {
      id: '/attualita/'
      path: '/'
      fullPath: '/attualita/'
      preLoaderRoute: typeof AttualitaIndexRouteImport
      parentRoute: typeof AttualitaRoute
    }
    '/attualita/$area': {
      id: '/attualita/$area'
      path: '/$area'
      fullPath: '/attualita/$area'
      preLoaderRoute: typeof AttualitaAreaRouteImport
      parentRoute: typeof AttualitaRoute
    }
    '/normativa/': {
      id: '/normativa/'
      path: '/'
      fullPath: '/normativa/'
      preLoaderRoute: typeof NormativaIndexRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/country-profiles': {
      id: '/normativa/country-profiles'
      path: '/country-profiles'
      fullPath: '/normativa/country-profiles'
      preLoaderRoute: typeof NormativaCountryProfilesRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/italia': {
      id: '/normativa/italia'
      path: '/italia'
      fullPath: '/normativa/italia'
      preLoaderRoute: typeof NormativaItaliaRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/ocse': {
      id: '/normativa/ocse'
      path: '/ocse'
      fullPath: '/normativa/ocse'
      preLoaderRoute: typeof NormativaOcseRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/pillar-two': {
      id: '/normativa/pillar-two'
      path: '/pillar-two'
      fullPath: '/normativa/pillar-two'
      preLoaderRoute: typeof NormativaPillarTwoRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/unione-europea': {
      id: '/normativa/unione-europea'
      path: '/unione-europea'
      fullPath: '/normativa/unione-europea'
      preLoaderRoute: typeof NormativaUnioneEuropeaRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/tool/': {
      id: '/tool/'
      path: '/tool'
      fullPath: '/tool/'
      preLoaderRoute: typeof ToolIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/bilancio-finder': {
      id: '/tool/bilancio-finder'
      path: '/tool/bilancio-finder'
      fullPath: '/tool/bilancio-finder'
      preLoaderRoute: typeof ToolBilancioFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/company-finder': {
      id: '/tool/company-finder'
      path: '/tool/company-finder'
      fullPath: '/tool/company-finder'
      preLoaderRoute: typeof ToolCompanyFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normativa/portale-interpelli/': {
      id: '/normativa/portale-interpelli/'
      path: '/portale-interpelli'
      fullPath: '/normativa/portale-interpelli/'
      preLoaderRoute: typeof NormativaPortaleInterpelliIndexRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/normativa/portale-interpelli/$id': {
      id: '/normativa/portale-interpelli/$id'
      path: '/portale-interpelli/$id'
      fullPath: '/normativa/portale-interpelli/$id'
      preLoaderRoute: typeof NormativaPortaleInterpelliIdRouteImport
      parentRoute: typeof NormativaRoute
    }
    '/tool/amount-b/': {
      id: '/tool/amount-b/'
      path: '/tool/amount-b'
      fullPath: '/tool/amount-b/'
      preLoaderRoute: typeof ToolAmountBIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/portale-interpelli/': {
      id: '/tool/portale-interpelli/'
      path: '/tool/portale-interpelli'
      fullPath: '/tool/portale-interpelli/'
      preLoaderRoute: typeof ToolPortaleInterpelliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool/portale-interpelli/$id': {
      id: '/tool/portale-interpelli/$id'
      path: '/tool/portale-interpelli/$id'
      fullPath: '/tool/portale-interpelli/$id'
      preLoaderRoute: typeof ToolPortaleInterpelliIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AttualitaRouteChildren {
  AttualitaAreaRoute: typeof AttualitaAreaRoute
  AttualitaIndexRoute: typeof AttualitaIndexRoute
}

const AttualitaRouteChildren: AttualitaRouteChildren = {
  AttualitaAreaRoute: AttualitaAreaRoute,
  AttualitaIndexRoute: AttualitaIndexRoute,
}

const AttualitaRouteWithChildren = AttualitaRoute._addFileChildren(
  AttualitaRouteChildren,
)

interface NormativaRouteChildren {
  NormativaCountryProfilesRoute: typeof NormativaCountryProfilesRoute
  NormativaItaliaRoute: typeof NormativaItaliaRoute
  NormativaOcseRoute: typeof NormativaOcseRoute
  NormativaPillarTwoRoute: typeof NormativaPillarTwoRoute
  NormativaUnioneEuropeaRoute: typeof NormativaUnioneEuropeaRoute
  NormativaIndexRoute: typeof NormativaIndexRoute
  NormativaPortaleInterpelliIdRoute: typeof NormativaPortaleInterpelliIdRoute
  NormativaPortaleInterpelliIndexRoute: typeof NormativaPortaleInterpelliIndexRoute
}

const NormativaRouteChildren: NormativaRouteChildren = {
  NormativaCountryProfilesRoute: NormativaCountryProfilesRoute,
  NormativaItaliaRoute: NormativaItaliaRoute,
  NormativaOcseRoute: NormativaOcseRoute,
  NormativaPillarTwoRoute: NormativaPillarTwoRoute,
  NormativaUnioneEuropeaRoute: NormativaUnioneEuropeaRoute,
  NormativaIndexRoute: NormativaIndexRoute,
  NormativaPortaleInterpelliIdRoute: NormativaPortaleInterpelliIdRoute,
  NormativaPortaleInterpelliIndexRoute: NormativaPortaleInterpelliIndexRoute,
}

const NormativaRouteWithChildren = NormativaRoute._addFileChildren(
  NormativaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttualitaRoute: AttualitaRouteWithChildren,
  AuthRoute: AuthRoute,
  GiurisprudenzaRoute: GiurisprudenzaRoute,
  McpRoute: McpRoute,
  NormativaRoute: NormativaRouteWithChildren,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ToolBilancioFinderRoute: ToolBilancioFinderRoute,
  ToolCompanyFinderRoute: ToolCompanyFinderRoute,
  ToolIndexRoute: ToolIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ToolPortaleInterpelliIdRoute: ToolPortaleInterpelliIdRoute,
  ToolAmountBIndexRoute: ToolAmountBIndexRoute,
  ToolPortaleInterpelliIndexRoute: ToolPortaleInterpelliIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
